import { Passage, Level } from '@/types';

// Level 1: Robert Louis Stevenson – A Child's Garden of Verses (public domain)
const level1Passages: Passage[] = [
  { id: 'l1-01', level: 1, title: 'Bed in Summer', author: 'Robert Louis Stevenson', content: 'In winter I get up at night And dress by yellow candle-light. In summer, quite the other way, I have to go to bed by day. I have to go to bed and see The birds still hopping on the tree, Or hear the grown-up people\'s feet Still going past me in the street. And does it not seem hard to you, When all the sky is clear and blue, And I should like so much to play, To have to go to bed by day?', hasAudio: true },
  { id: 'l1-02', level: 1, title: 'Time to Rise', author: 'Robert Louis Stevenson', content: 'A birdie with a yellow bill Hopped upon my window sill, Cocked his shining eye and said: "Ain\'t you \'shamed, you sleepy-head?" I lay and thought, this cannot be: But the very birdie said to me: "Why, you are in bed so late, Are you very ill or very great?" Now, to be ill is no delight; But to be great, I think it right. So every morning, in my bed, I wake and think I\'m very great.', hasAudio: true },
  { id: 'l1-03', level: 1, title: 'The Cow', author: 'Robert Louis Stevenson', content: 'The friendly cow all red and white, I love with all my heart: She gives me cream with all her might, To eat with apple-tart. She wanders lowing here and there, And yet she cannot stray, All in the pleasant open air, The pleasant light of day; And blown by all the winds that pass And wet with all the showers, She walks among the meadow grass And eats the meadow flowers.', hasAudio: true },
  { id: 'l1-04', level: 1, title: 'The Wind', author: 'Robert Louis Stevenson', content: 'I saw you toss the kites on high And blow the birds about the sky; And all around I heard you pass, Like ladies\' skirts across the grass. O wind, a-blowing all day long, O wind, that sings so loud a song! I saw the different things you did, But always you yourself you hid. I felt you push, I heard you call, I could not see yourself at all: O wind, a-blowing all day long, O wind, that sings so loud a song!', hasAudio: true },
  { id: 'l1-05', level: 1, title: 'Rain', author: 'Robert Louis Stevenson', content: 'The rain is raining all around, It falls on field and tree, It rains on the umbrellas here, And on the ships at sea.', hasAudio: true },
  { id: 'l1-06', level: 1, title: 'My Shadow', author: 'Robert Louis Stevenson', content: 'I have a little shadow that goes in and out with me, And what can be the use of him is more than I can see. He is very, very like me from the heels up to the head; And I see him jump before me, when I jump into my bed. The funniest thing about him is the way he likes to grow— Not at all like proper children, which is always very slow; For he sometimes shoots up taller like an india-rubber ball, And he sometimes gets so little that there\'s none of him at all. He hasn\'t got a notion of how children ought to play, And can only make a fool of me in every sort of way. He stays so close beside me, he\'s a coward you can see; I\'d think shame to stick to nursie as that shadow sticks to me!', hasAudio: true },
  { id: 'l1-07', level: 1, title: 'The Swing', author: 'Robert Louis Stevenson', content: 'How do you like to go up in a swing, Up in the air so blue? Oh, I do think it the pleasantest thing Ever a child can do! Up in the air and over the wall, Till I can see so wide, Rivers and trees and cattle and all Over the countryside— Till I look down on the garden green, Down on the roof so brown— Up in the air I go flying again, Up in the air and down!', hasAudio: true },
  { id: 'l1-08', level: 1, title: 'Happy Thought', author: 'Robert Louis Stevenson', content: 'The world is so full of a number of things, I\'m sure we should all be as happy as kings.', hasAudio: true },
  { id: 'l1-09', level: 1, title: 'A Thought', author: 'Robert Louis Stevenson', content: 'It is very nice to think The world is full of meat and drink, With little children saying grace In every Christian kind of place.', hasAudio: true },
  { id: 'l1-10', level: 1, title: 'Where Go the Boats?', author: 'Robert Louis Stevenson', content: 'Dark brown is the river, Golden is the sand. It flows along for ever, With trees on either hand. Green leaves a-floating, Castles of the foam, Boats of mine a-boating— Where will all come home? On goes the river And out past the mill, Away down the valley, Away down the hill. Away down the river, A hundred miles or more, Other little children Shall bring my boats ashore.', hasAudio: true },
];

// Level 2: Traditional Nursery Rhymes (public domain)
const level2Passages: Passage[] = [
  { id: 'l2-01', level: 2, title: 'Twinkle, Twinkle, Little Star', author: 'Traditional', content: 'Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, Like a diamond in the sky. Twinkle, twinkle, little star, How I wonder what you are!', hasAudio: true },
  { id: 'l2-02', level: 2, title: 'Baa, Baa, Black Sheep', author: 'Traditional', content: 'Baa, baa, black sheep, Have you any wool? Yes sir, yes sir, Three bags full; One for the master, And one for the dame, And one for the little boy Who lives down the lane.', hasAudio: true },
  { id: 'l2-03', level: 2, title: 'Jack and Jill', author: 'Traditional', content: 'Jack and Jill went up the hill To fetch a pail of water; Jack fell down and broke his crown, And Jill came tumbling after. Up Jack got and home did trot, As fast as he could caper; Went to bed to mend his head With vinegar and brown paper.', hasAudio: true },
  { id: 'l2-04', level: 2, title: 'Humpty Dumpty', author: 'Traditional', content: 'Humpty Dumpty sat on a wall, Humpty Dumpty had a great fall; All the king\'s horses and all the king\'s men Couldn\'t put Humpty together again.', hasAudio: true },
  { id: 'l2-05', level: 2, title: 'Mary Had a Little Lamb', author: 'Traditional', content: 'Mary had a little lamb, Its fleece was white as snow; And everywhere that Mary went, The lamb was sure to go. It followed her to school one day, Which was against the rule; It made the children laugh and play, To see a lamb at school.', hasAudio: true },
  { id: 'l2-06', level: 2, title: 'Hickory Dickory Dock', author: 'Traditional', content: 'Hickory dickory dock, The mouse ran up the clock. The clock struck one, The mouse ran down, Hickory dickory dock.', hasAudio: true },
  { id: 'l2-07', level: 2, title: 'Hey Diddle Diddle', author: 'Traditional', content: 'Hey diddle diddle, The cat and the fiddle, The cow jumped over the moon; The little dog laughed To see such sport, And the dish ran away with the spoon.', hasAudio: true },
  { id: 'l2-08', level: 2, title: 'Little Miss Muffet', author: 'Traditional', content: 'Little Miss Muffet Sat on a tuffet, Eating her curds and whey; There came a big spider Who sat down beside her And frightened Miss Muffet away.', hasAudio: true },
  { id: 'l2-09', level: 2, title: 'Little Bo-Peep', author: 'Traditional', content: 'Little Bo-Peep has lost her sheep, And doesn\'t know where to find them; Leave them alone, and they\'ll come home, Wagging their tails behind them. Little Bo-Peep fell fast asleep, And dreamed she heard them bleating; But when she awoke, she found it a joke, For they were still a-fleeting.', hasAudio: true },
  { id: 'l2-10', level: 2, title: 'London Bridge Is Falling Down', author: 'Traditional', content: 'London Bridge is falling down, Falling down, falling down, London Bridge is falling down, My fair lady. Build it up with sticks and stones, Sticks and stones, sticks and stones, Build it up with sticks and stones, My fair lady.', hasAudio: true },
  { id: 'l2-11', level: 2, title: 'Old Mother Hubbard', author: 'Traditional', content: 'Old Mother Hubbard Went to the cupboard To give the poor dog a bone; But when she got there The cupboard was bare, And so the poor dog had none. She went to the baker\'s To buy him some bread; But when she came back The poor dog was dead.', hasAudio: true },
  { id: 'l2-12', level: 2, title: 'Simple Simon', author: 'Traditional', content: 'Simple Simon met a pieman Going to the fair; Says Simple Simon to the pieman, "Let me taste your ware." Says the pieman to Simple Simon, "Show me first your penny;" Says Simple Simon to the pieman, "Indeed I have not any."', hasAudio: true },
  { id: 'l2-13', level: 2, title: 'Sing a Song of Sixpence', author: 'Traditional', content: 'Sing a song of sixpence, A pocket full of rye; Four and twenty blackbirds Baked in a pie. When the pie was opened, The birds began to sing; Wasn\'t that a dainty dish, To set before the king?', hasAudio: true },
  { id: 'l2-14', level: 2, title: 'Row, Row, Row Your Boat', author: 'Traditional', content: 'Row, row, row your boat, Gently down the stream. Merrily, merrily, merrily, merrily, Life is but a dream.', hasAudio: true },
  { id: 'l2-15', level: 2, title: 'Rain, Rain, Go Away', author: 'Traditional', content: 'Rain, rain, go away, Come again another day; Little Johnny wants to play.', hasAudio: true },
];

// Level 3: Aesop's Fables (public domain)
const level3Passages: Passage[] = [
  { id: 'l3-01', level: 3, title: 'The Fox and the Grapes', author: 'Aesop', content: 'A hungry Fox saw some fine bunches of grapes hanging from a vine that was trained along a high trellis. He did his best to reach them by jumping as high as he could into the air. But it was all in vain, for they were just out of reach. So he gave up trying and walked away with an air of dignity and unconcern, remarking, "I thought those grapes were ripe, but I see now they are quite sour." Moral: It is easy to despise what you cannot get.', hasAudio: true },
  { id: 'l3-02', level: 3, title: 'The Tortoise and the Hare', author: 'Aesop', content: 'A Hare once boasted of his speed. "I have never yet been beaten," said he, "when I put forth my full speed." The Tortoise quietly said, "I accept your challenge." The race began. The Hare soon left the Tortoise far behind and lay down for a nap. The Tortoise kept going slowly but steadily and passed the sleeping Hare. When the Hare awoke, he ran as fast as he could, but it was too late. Moral: Slow and steady wins the race.', hasAudio: true },
  { id: 'l3-03', level: 3, title: 'The Boy Who Cried Wolf', author: 'Aesop', content: 'A shepherd boy often amused himself by crying out, "Wolf! Wolf!" though there was no wolf. The villagers came to help him and found it was only a trick. One day a wolf really came. The boy cried out, "Wolf! Wolf!" but the villagers thought he was joking and did not come. The wolf scattered the flock. Moral: Liars are not believed even when they speak the truth.', hasAudio: true },
  { id: 'l3-04', level: 3, title: 'The Ant and the Grasshopper', author: 'Aesop', content: 'In summer the Ant worked hard to gather food, while the Grasshopper sang and danced. "Why not rest?" asked the Grasshopper. "Winter is far away." But when winter came, the Grasshopper had nothing to eat, and the Ant had plenty. Moral: It is best to prepare for days of need.', hasAudio: true },
  { id: 'l3-05', level: 3, title: 'The Lion and the Mouse', author: 'Aesop', content: 'A Lion caught a Mouse and was about to kill him. "Spare me," said the Mouse, "and I may repay you someday." The Lion laughed but let him go. Later, the Lion was caught in a hunter\'s net. The Mouse gnawed the ropes and set him free. Moral: Little friends may prove great friends.', hasAudio: true },
  { id: 'l3-06', level: 3, title: 'The Crow and the Pitcher', author: 'Aesop', content: 'A thirsty Crow found a pitcher with a little water at the bottom. She could not reach it. She dropped pebbles into the pitcher until the water rose high enough to drink. Moral: Where there is a will, there is a way.', hasAudio: true },
  { id: 'l3-07', level: 3, title: 'The Dog and the Shadow', author: 'Aesop', content: 'A Dog carrying a piece of meat crossed a bridge. Seeing his reflection in the water, he thought it was another dog with a bigger piece. He snapped at it and dropped his own meat into the stream. Moral: Beware lest you lose the substance by grasping at the shadow.', hasAudio: true },
  { id: 'l3-08', level: 3, title: 'The Goose with the Golden Eggs', author: 'Aesop', content: 'A man owned a goose that laid a golden egg every day. Thinking to get all the gold at once, he killed the goose, only to find nothing inside. Moral: Greed often overreaches itself.', hasAudio: true },
  { id: 'l3-09', level: 3, title: 'The Wolf in Sheep\'s Clothing', author: 'Aesop', content: 'A Wolf disguised himself in a sheep\'s skin and mingled with the flock. At night, he was shut in with the sheep and was killed by the shepherd. Moral: The evildoer often brings about his own destruction.', hasAudio: true },
  { id: 'l3-10', level: 3, title: 'The Town Mouse and the Country Mouse', author: 'Aesop', content: 'A Country Mouse visited a Town Mouse and was amazed at the rich food. But they were frightened by dogs and noise. The Country Mouse returned home, saying, "Better simple fare in peace than luxury in fear." Moral: Better a humble life in safety than wealth with danger.', hasAudio: true },
  { id: 'l3-11', level: 3, title: 'The Milkmaid and Her Pail', author: 'Aesop', content: 'A Milkmaid carried milk on her head and dreamed of selling it, buying eggs, and becoming rich. She tossed her head proudly and spilled the milk. Moral: Do not count your chickens before they are hatched.', hasAudio: true },
  { id: 'l3-12', level: 3, title: 'The Fisherman and the Little Fish', author: 'Aesop', content: 'A Fisherman caught a little fish. "Let me go," said the fish, "and I will grow larger." But the Fisherman replied, "A small gain now is better than a chance of a larger one later." Moral: A bird in the hand is worth two in the bush.', hasAudio: true },
  { id: 'l3-13', level: 3, title: 'The North Wind and the Sun', author: 'Aesop', content: 'The North Wind and the Sun argued which was stronger. They agreed whoever could make a traveler remove his cloak would win. The Wind blew fiercely, but the traveler wrapped his cloak tighter. The Sun shone warmly, and the traveler removed it. Moral: Gentleness and kindness are stronger than force.', hasAudio: true },
  { id: 'l3-14', level: 3, title: 'The Bundle of Sticks', author: 'Aesop', content: 'An old man gave his sons a bundle of sticks and told them to break it. They could not. He then untied it and gave them the sticks one by one, which they broke easily. Moral: Unity is strength.', hasAudio: true },
  { id: 'l3-15', level: 3, title: 'Hercules and the Wagoner', author: 'Aesop', content: 'A wagoner stuck in the mud called upon Hercules for help. Hercules appeared and said, "Put your shoulder to the wheel and try yourself before asking for help." Moral: The gods help those who help themselves.', hasAudio: true },
  { id: 'l3-16', level: 3, title: 'The Fox and the Crow', author: 'Aesop', content: 'A Crow sat with cheese in her beak. A Fox flattered her and asked her to sing. She opened her beak, and the cheese fell. The Fox seized it. Moral: Do not trust flatterers.', hasAudio: true },
  { id: 'l3-17', level: 3, title: 'The Fox and the Stork', author: 'Aesop', content: 'A Fox invited a Stork to dinner and served soup in a shallow dish. The Stork could not eat it. Later, the Stork served dinner in a tall jar. The Fox could not reach it. Moral: One bad turn deserves another.', hasAudio: true },
  { id: 'l3-18', level: 3, title: 'The Fox and the Goat', author: 'Aesop', content: 'A Fox fell into a well and could not get out. A Goat asked why he was there. The Fox tricked the Goat into jumping in. Then he climbed on the Goat\'s back and escaped, leaving the Goat behind. Moral: Look before you leap.', hasAudio: true },
  { id: 'l3-19', level: 3, title: 'The Oak and the Reeds', author: 'Aesop', content: 'A mighty Oak laughed at the Reeds for bending in the wind. A great storm came, and the Oak was uprooted, while the Reeds survived by bending. Moral: Better to bend than to break.', hasAudio: true },
  { id: 'l3-20', level: 3, title: 'The Mice in Council', author: 'Aesop', content: 'The Mice met to plan how to protect themselves from the Cat. One suggested hanging a bell around the Cat\'s neck so they would hear her coming. All agreed it was a good idea, but none would volunteer to do it. Moral: It is one thing to say what should be done, and another to do it.', hasAudio: true },
];

// Level 4: Robert Louis Stevenson - A Child's Garden of Verses (public domain)
const level4Passages: Passage[] = [
  { id: 'l4-01', level: 4, title: 'From a Railway Carriage', author: 'Robert Louis Stevenson', content: 'Faster than fairies, faster than witches, Bridges and houses, hedges and ditches; And charging along like troops in a battle, All through the meadows the horses and cattle: All of the sights of the hill and the plain Fly as thick as driving rain; And ever again, in the wink of an eye, Painted stations whistle by. Here is a child who clambers and scrambles, All by himself and gathering brambles; Here is a tramp who stands and gazes; And here is the green for stringing the daisies! Here is a cart run away in the road Lumping along with man and load; And here is a mill and there is a river: Each a glimpse and gone for ever!', hasAudio: true },
  { id: 'l4-02', level: 4, title: 'Foreign Lands', author: 'Robert Louis Stevenson', content: 'Up into the cherry tree Who should climb but little me? I held the trunk with both my hands And looked abroad on foreign lands. I saw the next door garden lie, Adorned with flowers, before my eye, And many pleasant places more That I had never seen before. I saw the dimpling river pass And be the sky\'s blue looking-glass; The dusty roads go up and down With people tramping into town. If I could find a higher tree Farther and farther I should see, To where the grown-up river slips Into the sea among the ships; To where the roads on either hand Lead onward into fairy land, Where all the children dine at five, And all the playthings come alive.', hasAudio: true },
  { id: 'l4-03', level: 4, title: 'The Lamplighter', author: 'Robert Louis Stevenson', content: 'My tea is nearly ready and the sun has left the sky; It\'s time to take the window to see Leerie going by; For every night at teatime and before you take your seat, With lantern and with ladder he comes posting up the street. Now Tom would be a driver and Maria go to sea, And my papa\'s a banker and as rich as he can be; But I, when I am stronger and can choose what I\'m to do, O Leerie, I\'ll go round at night and light the lamps with you!', hasAudio: true },
  { id: 'l4-04', level: 4, title: 'The Moon', author: 'Robert Louis Stevenson', content: 'The moon has a face like the clock in the hall; She shines on thieves on the garden wall, On streets and fields and harbor quays, And birdies asleep in the forks of the trees. The squalling cat and the squeaking mouse, The howling dog by the door of the house, The bat that lies in bed at noon, All love to be out by the light of the moon. But all of the things that belong to the day Cuddle to sleep to be out of her way; And flowers and children close their eyes Till up in the morning the sun shall arise.', hasAudio: true },
  { id: 'l4-05', level: 4, title: 'The Land of Nod', author: 'Robert Louis Stevenson', content: 'From breakfast on through all the day At home among my friends I stay; But every night I go abroad Afar into the Land of Nod. All by myself I have to go, With none to tell me what to do— All alone beside the streams And up the mountain-sides of dreams. The strangest things are these for me, Both things to eat and things to see, And many frightening sights abroad Till morning in the Land of Nod. Try as I like to find the way, I never can get back by day, Nor can remember plain and clear The curious music that I hear.', hasAudio: true },
  { id: 'l4-06', level: 4, title: 'The Land of Counterpane', author: 'Robert Louis Stevenson', content: 'When I was sick and lay a-bed, I had two pillows at my head, And all my toys beside me lay To keep me happy all the day. And sometimes for an hour or so I watched my leaden soldiers go, With different uniforms and drills, Among the bed-clothes, through the hills;', hasAudio: true },
  { id: 'l4-07', level: 4, title: 'My Bed is a Boat', author: 'Robert Louis Stevenson', content: 'My bed is like a little boat; Nurse helps me in when I embark; She girds me in my sailor\'s coat And starts me in the dark. At night I go on board and say Good-night to all my friends on shore; I shut my eyes and sail away And see and hear no more.', hasAudio: true },
  { id: 'l4-08', level: 4, title: 'Escape at Bedtime', author: 'Robert Louis Stevenson', content: 'The lights from the parlour and kitchen shone out Through the blinds and the windows and bars; And high overhead and all moving about, There were thousands of millions of stars.', hasAudio: true },
  { id: 'l4-09', level: 4, title: 'Marching Song', author: 'Robert Louis Stevenson', content: 'Bring the comb and play upon it! Marching, here we come! Willie cocks his highland bonnet, Johnnie beats the drum.', hasAudio: true },
  { id: 'l4-10', level: 4, title: 'Looking-Glass River', author: 'Robert Louis Stevenson', content: 'Smooth it glides upon its travel, Here a wimple, there a gleam— O the clean gravel! O the smooth stream!', hasAudio: true },
  { id: 'l4-11', level: 4, title: 'Fairy Bread', author: 'Robert Louis Stevenson', content: 'Come up here, O dusty feet! Here is fairy bread to eat.', hasAudio: true },
  { id: 'l4-12', level: 4, title: 'At the Sea-side', author: 'Robert Louis Stevenson', content: 'When I was down beside the sea A wooden spade they gave to me To dig the sandy shore.', hasAudio: true },
  { id: 'l4-13', level: 4, title: 'Whole Duty of Children', author: 'Robert Louis Stevenson', content: 'A child should always say what\'s true And speak when he is spoken to.', hasAudio: true },
  { id: 'l4-14', level: 4, title: 'Travel', author: 'Robert Louis Stevenson', content: 'I should like to rise and go Where the golden apples grow;', hasAudio: true },
  { id: 'l4-15', level: 4, title: 'Singing', author: 'Robert Louis Stevenson', content: 'Of speckled eggs the birdie sings And nests among the trees;', hasAudio: true },
  { id: 'l4-16', level: 4, title: 'Looking Forward', author: 'Robert Louis Stevenson', content: 'When I am grown to man\'s estate I shall be very proud and great;', hasAudio: true },
  { id: 'l4-17', level: 4, title: 'Winter-Time', author: 'Robert Louis Stevenson', content: 'Late lies the wintry sun a-bed, A frosty, fiery sleepy-head;', hasAudio: true },
  { id: 'l4-18', level: 4, title: 'The Hayloft', author: 'Robert Louis Stevenson', content: 'Through all the pleasant meadow-side The grass grew shoulder-high;', hasAudio: true },
  { id: 'l4-19', level: 4, title: 'North-West Passage', author: 'Robert Louis Stevenson', content: 'Good-night, good-night, and when we wake The sunshine will be bright;', hasAudio: true },
  { id: 'l4-20', level: 4, title: 'Windy Nights', author: 'Robert Louis Stevenson', content: 'Whenever the moon and stars are set, Whenever the wind is high,', hasAudio: true },
  { id: 'l4-21', level: 4, title: 'System', author: 'Robert Louis Stevenson', content: 'Every night my prayers I say, And get my dinner every day;', hasAudio: true },
  { id: 'l4-22', level: 4, title: 'The Sun Travels', author: 'Robert Louis Stevenson', content: 'The sun is not a-bed, when I At night upon my pillow lie;', hasAudio: true },
  { id: 'l4-23', level: 4, title: 'The Little Land', author: 'Robert Louis Stevenson', content: 'When at home alone I sit And am very tired of it,', hasAudio: true },
  { id: 'l4-24', level: 4, title: 'To Any Reader', author: 'Robert Louis Stevenson', content: 'As from the house your mother sees You playing round the garden trees,', hasAudio: true },
  { id: 'l4-25', level: 4, title: 'A Good Play', author: 'Robert Louis Stevenson', content: 'We built a ship upon the stairs All made of the back-bedroom chairs,', hasAudio: true },
];

// Level 5: Classic Children's Literature excerpts (public domain)
const level5Passages: Passage[] = [
  { id: 'l5-01', level: 5, title: 'Cinderella (excerpt)', author: 'Andrew Lang (ed.)', content: 'There was once a gentleman who married, for his second wife, the proudest and most haughty woman that was ever seen. She had two daughters of her own humor, who were exactly like her in all things. The husband had likewise by another wife a young daughter, but of unparalleled goodness and sweetness of temper. Her mother had been the best creature in the world, and she took after her. No sooner were the ceremonies of the wedding over than the stepmother began to show herself in her true colors. She could not bear the good qualities of this pretty girl, and the less because they made her own daughters appear the more odious. She employed her in the meanest work of the house: she scoured the dishes and tables, cleaned the chambers of her mistress and her daughters, and slept in a sorry garret, upon a wretched straw bed.', hasAudio: true },
  { id: 'l5-02', level: 5, title: 'Sleeping Beauty in the Wood (excerpt)', author: 'Andrew Lang (ed.)', content: 'There were formerly a king and queen who were so sorry that they had no children that it cannot be expressed. At last, however, the queen had a daughter. They held a great christening feast. They invited all the fairies they could find in the country. After the feast, the fairies gave their gifts to the child. One gave her beauty, another wit, another grace. But an old fairy, who had not been invited, entered the hall in anger and pronounced a dreadful prophecy: that the princess would prick her hand with a spindle and die.', hasAudio: true },
  { id: 'l5-03', level: 5, title: 'Little Red Riding Hood (excerpt)', author: 'Andrew Lang (ed.)', content: 'Once upon a time there lived in a certain village a little country girl, the prettiest creature who was ever seen. Her mother was excessively fond of her; and her grandmother doted on her still more. This good woman had a little red riding hood made for her. It suited the girl so extremely well that everybody called her Little Red Riding Hood. One day her mother said to her, "Go, my dear, and see how your grandmother is doing, for I hear she has been very ill. Take her a cake and this little pot of butter." Little Red Riding Hood set out immediately to go to her grandmother, who lived in another village.', hasAudio: true },
  { id: 'l5-04', level: 5, title: 'Beauty and the Beast (excerpt)', author: 'Andrew Lang (ed.)', content: 'Once upon a time there was a merchant who was exceedingly rich. He had six children, three sons and three daughters. The youngest daughter was so beautiful that she was called Beauty. One day the merchant lost all his wealth and was obliged to move into a small house in the country. Beauty bore this misfortune with patience, while her sisters complained bitterly. Later, when the merchant journeyed to recover some property, he lost his way in a forest and found himself before a magnificent palace.', hasAudio: true },
  { id: 'l5-05', level: 5, title: 'Aladdin and the Wonderful Lamp (excerpt)', author: 'Andrew Lang (ed.)', content: 'There once lived in a large and rich city of China a tailor named Mustapha, who had a son called Aladdin. Aladdin was a careless and idle boy who would do nothing but play in the streets with little idle boys like himself. This so grieved his father that he died. After his father\'s death, a stranger came to the town and pretended to be Aladdin\'s uncle. He persuaded the boy to come with him on a journey, promising him wealth and fine clothes.', hasAudio: true },
  { id: 'l5-06', level: 5, title: 'Hansel and Gretel (excerpt)', author: 'Brothers Grimm', content: 'Hard by a great forest dwelt a poor woodcutter with his wife and his two children. The boy was called Hansel and the girl Gretel. One evening the father said, "What will become of us? How shall we feed our poor children?" The stepmother answered coldly, "We will lead them into the forest and leave them there." Hansel overheard and filled his pockets with little white pebbles. When they were left in the forest, he dropped the stones along the path. By moonlight they followed the shining pebbles home. But the second time, Hansel had only bread crumbs, and birds ate them. The children wandered deeper into the forest until they saw a little house made of bread and sugar.', hasAudio: true },
  { id: 'l5-07', level: 5, title: 'Snow-White (excerpt)', author: 'Brothers Grimm', content: 'Once upon a time in the middle of winter, when the snowflakes were falling like feathers from the sky, a queen sat sewing by her window. She pricked her finger and three drops of blood fell upon the snow. "Oh, that I had a child as white as snow, as red as blood, and as black as ebony," she said. Soon a little daughter was born, and she was called Snow-White. After the queen died, the king married again, and the new queen was proud and wicked, and she could not bear that anyone should be more beautiful than she.', hasAudio: true },
  { id: 'l5-08', level: 5, title: 'Rumpelstiltskin (excerpt)', author: 'Brothers Grimm', content: 'There was once a miller who had a beautiful daughter. One day he boasted to the king that his daughter could spin straw into gold. The king locked her in a room full of straw and said, "Spin this into gold by morning, or you shall die." The girl sat weeping. Suddenly a little man appeared. "What will you give me if I spin the straw into gold?" he asked. She gave him her necklace, and he spun the straw into shining gold.', hasAudio: true },
  { id: 'l5-09', level: 5, title: 'The Brave Little Tailor (excerpt)', author: 'Brothers Grimm', content: 'A little tailor sat on his table one morning eating bread and jam. Flies gathered upon it, and he struck them with a cloth, killing seven at one blow. Proud of his deed, he stitched a belt reading, "Seven at one blow." Then he set out into the world to seek his fortune. People thought he meant he had killed seven men, and they feared him greatly.', hasAudio: true },
  { id: 'l5-10', level: 5, title: 'The Happy Prince (excerpt)', author: 'Oscar Wilde', content: 'High above the city, on a tall column, stood the statue of the Happy Prince. He was gilded all over with thin leaves of fine gold, and for eyes he had two bright sapphires. One night a little Swallow flew over the city. He saw the statue and rested between the feet of the Happy Prince. As he slept, a large drop of water fell on him. It was a tear. "Why are you weeping?" asked the Swallow. The Prince replied, "When I was alive and had a human heart, I did not know what sorrow was. Now I see all the misery of my city.', hasAudio: true },
  { id: 'l5-11', level: 5, title: 'Alice\'s Adventures in Wonderland (excerpt)', author: 'Lewis Carroll', content: 'Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do. Suddenly a White Rabbit with pink eyes ran close by her. There was nothing so very remarkable in that; but when the Rabbit actually took a watch out of its waistcoat-pocket and looked at it, Alice started to her feet. Burning with curiosity, she ran across the field after it and was just in time to see it pop down a large rabbit-hole under the hedge.', hasAudio: true },
  { id: 'l5-12', level: 5, title: 'The Wonderful Wizard of Oz (excerpt)', author: 'L. Frank Baum', content: 'Dorothy lived in the midst of the great Kansas prairies, with Uncle Henry and Aunt Em. One day a cyclone came sweeping across the land. The house was lifted from its foundations and carried high into the air. When Dorothy awoke, she found herself in a strange land of marvelous beauty, and a little old woman thanked her for killing the Wicked Witch of the East.', hasAudio: true },
  { id: 'l5-13', level: 5, title: 'The Secret Garden (excerpt)', author: 'Frances Hodgson Burnett', content: 'When Mary Lennox was sent to Misselthwaite Manor, she was a thin, fretful child who had never learned to care for others. One day she heard a curious sound behind a wall in the garden. She discovered a hidden door and a key buried in the earth. Beyond the door lay a secret garden that had been locked for many years.', hasAudio: true },
  { id: 'l5-14', level: 5, title: 'Just So Stories (excerpt)', author: 'Rudyard Kipling', content: 'In the High and Far-Off Times the Elephant had no trunk. He had only a small nose, like a boot. But a Crocodile seized him by the nose and pulled and pulled until it stretched into a long trunk. And that is how the Elephant got his trunk, my Best Beloved.', hasAudio: true },
  { id: 'l5-15', level: 5, title: 'A Christmas Carol (opening excerpt)', author: 'Charles Dickens', content: 'Marley was dead: to begin with. There is no doubt whatever about that. Scrooge never painted out Old Marley\'s name. There it stood, years afterwards, above the warehouse door. Oh! But he was a tight-fisted hand at the grindstone, Scrooge! A squeezing, wrenching, grasping, scraping, clutching, covetous old sinner!', hasAudio: true },
  { id: 'l5-16', level: 5, title: 'Little Women (excerpt)', author: 'Louisa May Alcott', content: '“Christmas won\'t be Christmas without any presents,” grumbled Jo, lying on the rug. “We\'ve got Father and Mother, and each other,” said Beth softly. The four March sisters tried to be cheerful though money was scarce and their father was away at war. Yet even in hardship, their home was warm with kindness and hope.', hasAudio: true },
  { id: 'l5-17', level: 5, title: 'Peter Pan (excerpt)', author: 'J. M. Barrie', content: 'All children, except one, grow up. They soon know that they will grow up, and the way Wendy knew was this: one day when she was two years old she was playing in a garden, and she plucked another flower and ran with it to her mother. Mrs. Darling put her hand to her heart and said, “Oh, why can’t you remain like this forever!”', hasAudio: true },
  { id: 'l5-18', level: 5, title: 'Treasure Island (excerpt)', author: 'Robert Louis Stevenson', content: 'Squire Trelawney, Dr. Livesey, and the rest of these gentlemen having asked me to write down the whole particulars about Treasure Island, I take up my pen in the year of grace 17—. It was about this time that my father kept the Admiral Benbow inn, and the brown old seaman with the saber cut first took up his lodging under our roof.', hasAudio: true },
  { id: 'l5-19', level: 5, title: 'The Jungle Book (excerpt)', author: 'Rudyard Kipling', content: 'It was seven o\'clock of a very warm evening in the Seeonee hills when Father Wolf woke up from his day\'s rest. Mother Wolf lay with her four cubs beside her, and the moon shone into the mouth of the cave. Suddenly there came a shadow and a voice cried, “Good hunting!”', hasAudio: true },
  { id: 'l5-20', level: 5, title: 'The Call of the Wild (excerpt)', author: 'Jack London', content: 'Buck did not read the newspapers, or he would have known that trouble was brewing. He had lived the life of a pampered dog in Judge Miller’s place. But suddenly he was torn from that life and thrown into a harsh northern world of snow and struggle.', hasAudio: true },
  { id: 'l5-21', level: 5, title: 'The Wind in the Willows (excerpt)', author: 'Kenneth Grahame', content: 'The Mole had been working very hard all the morning, spring-cleaning his little home. Suddenly he flung down his brush and bolted out of the house into the sunshine. Something up above was calling him—spring itself was calling.', hasAudio: true },
  { id: 'l5-22', level: 5, title: 'Anne of Green Gables (excerpt)', author: 'L. M. Montgomery', content: 'Mrs. Rachel Lynde was sitting at her kitchen window, knitting. Down the road came a small, thin girl with bright eyes and red hair. She carried a worn carpetbag and looked about her with eager wonder.', hasAudio: true },
  { id: 'l5-23', level: 5, title: 'Black Beauty (excerpt)', author: 'Anna Sewell', content: 'The first place that I can well remember was a large pleasant meadow with a pond of clear water in it. My mother was a tall, handsome black mare, and I was her little dark colt.', hasAudio: true },
  { id: 'l5-24', level: 5, title: 'The Princess and the Goblin (excerpt)', author: 'George MacDonald', content: 'There was once a little princess whose father was king over a great country. Her mother had died when she was very young, and she lived in a lonely castle among the mountains.', hasAudio: true },
  { id: 'l5-25', level: 5, title: 'The Blue Fairy Book (general excerpt)', author: 'Andrew Lang (ed.)', content: 'In the days when wishes were granted and magic walked openly upon the earth, there lived kings and queens whose castles shone in the sunlight. Knights rode forth in shining armor, and dragons guarded secret treasures beneath the hills.', hasAudio: true },
  { id: 'l5-26', level: 5, title: 'The Swiss Family Robinson (excerpt)', author: 'Johann David Wyss', content: 'We were at sea in a violent storm. The waves rose like mountains and dashed against our ship. When at last the vessel struck upon a reef, we resolved to trust ourselves to Providence and seek safety upon a deserted shore.', hasAudio: true },
  { id: 'l5-27', level: 5, title: 'Robinson Crusoe (excerpt)', author: 'Daniel Defoe', content: 'I was born in the year 1632, in the city of York, of a good family. From my earliest youth I desired to go to sea, though my father warned me of the dangers that awaited reckless adventure.', hasAudio: true },
  { id: 'l5-28', level: 5, title: 'Gulliver\'s Travels (excerpt)', author: 'Jonathan Swift', content: 'My father had a small estate in Nottinghamshire; I was the third of five sons. At fourteen I was bound apprentice to a surgeon. After some years, I resolved to see the world and embarked upon a voyage.', hasAudio: true },
  { id: 'l5-29', level: 5, title: 'The Prince and the Pauper (excerpt)', author: 'Mark Twain', content: 'In the ancient city of London, on a certain autumn day in the second quarter of the sixteenth century, a boy was born to a poor family named Canty. On that same day, another boy was born to the royal house of Tudor. The whole kingdom rejoiced over the royal child, but no one cared for the pauper.', hasAudio: true },
  { id: 'l5-30', level: 5, title: 'A Christmas Carol (precision challenge excerpt)', author: 'Charles Dickens', content: 'Marley was dead: to begin with. There is no doubt whatever about that. Scrooge was his sole executor, his sole administrator, his sole assign, his sole residuary legatee, his sole friend, and sole mourner. Oh! But he was a tight-fisted hand at the grindstone, Scrooge! A squeezing, wrenching, grasping, scraping, clutching, covetous old sinner! Hard and sharp as flint, secret, and self-contained, and solitary as an oyster.', hasAudio: true },
];

export const ALL_PASSAGES: Passage[] = [
  ...level1Passages,
  ...level2Passages,
  ...level3Passages,
  ...level4Passages,
  ...level5Passages,
];

export function getPassagesByLevel(level: Level): Passage[] {
  return ALL_PASSAGES.filter((p) => p.level === level);
}

export function getPassageById(id: string): Passage | undefined {
  return ALL_PASSAGES.find((p) => p.id === id);
}

export function getNextPassage(level: Level, completedIds: string[]): Passage | undefined {
  const levelPassages = getPassagesByLevel(level);
  return levelPassages.find((p) => !completedIds.includes(p.id));
}
